### ISSUE TITLE
unbound method addHmac()  error

### ISSUE THREAD

**Issue by shiham101** [bao7uo/RAU_crypto#2]
Q1:How to mapping Telerik.Web.UI.WebResource version in this http response

 Version=4.0.0.0, CultureTelerik.Web.UI.WebResource.axd?_TSM_HiddenField_=ContentPlaceHolder_FormTop_RadScriptManager1_TSM&amp;compress=1&amp;_TSM_CombinedScripts_=;;System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35:zh-TW:8f95decb-d716-4257-bc42-c772df7173e5:ea597d4b:b25378d2;Telerik.Web.UI:zh-TW:df833b2e-28ee-45e7-8320-6f2a9cb883d7:16e4e7cd:f7645509:22a6274a:24ee1bba:6a6d718d

Q2 
How to fix unbound method addHmac() must be called with RAUCipher instance as first argument (got str instance instead)

log:
python 43874.py -P c:\\inetpub\\wwwroot 2017.2.503 43609.py https://target/Telerik.Web.UI.WebResource.axd?type=rau

file: 43609.py
version:2017.2.503
destination c:\inetpub\wwwroot
Preparing payload... 
Traceback (most recent call last):
  File "43874.py", line 322, in <module>
    mode_Post()
  File "43874.py", line 280, in mode_Post
    print(upload(TempTargetFolder, Version, payload_filename, url))
  File "43874.py", line 196, in upload
    payload_filename
  File "43874.py", line 158, in payload
    data += rauPostData_prep(quiet, TempTargetFolder, Version) + "\r\n"
  File "43874.py", line 103, in rauPostData_prep
    Version
TypeError: unbound method addHmac() must be called with RAUCipher instance as first argument (got str instance instead)

**Comment by Antonytm** [comment]
Q2: Use Python 3.6 with code from my pull request and pycryptodome library instead of pycrypto.

**Comment by Deepikajindal** [comment]
I am having same issue

**Comment by bao7uo** [comment]
Thanks everyone. @shiham101 and @Deepikajindal I have merged the PR from @Antonytm which should hopefully fix Q2. If Q1 is an issue with a vulnerable version of the Telerik Libraries then please create a new issue with a little more explanation as I'm not sure what you mean.
